steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - functions
  - deploy
  - userBackup
  - --source=CloudFunction
  - --region=$_REGION 
  - --runtime=python37
  - --trigger-event=google.pubsub.topic.publish
  - --trigger-resource=$_BACKUP_PUBSUB
  - --set-env-vars=pat_token=$_PAT_TOKEN,var_group_name=$_VAR_GROUP_NAME,env_name=$_ENV_NAME
  - --timeout=540s

- name: "gcr.io/cloud-builders/gcloud"
  entrypoint: "/bin/bash"
  args:
    - "-c"
    - |
      python3 -u slack/slack-notify.py;
  env:
    - 'PROJECT_ID=$PROJECT_ID'
    - 'BUILD_ID=$BUILD_ID'
    - 'REPO_NAME=$REPO_NAME'
    - 'COMMIT_SHA=$COMMIT_SHA'
    - 'SHORT_SHA=$SHORT_SHA'
    - 'SLACK_CHANNEL=$_SLACK_CHANNEL'
    - 'SLACK_WEBHOOK=$_SLACK_WEBHOOK'  
