parameters:
  - name : VarGroup
    displayName: Variable Group
  - name: Environment
    displayName: Environment to use

trigger:
- none

variables:
 - group: ${{ parameters.VarGroup }}
 - name: ServerParkName
   value: gusty
 - name: SurveyType
   value: OPN

stages:
 - stage: BackupUsers
   displayName: BackupUsers
   variables:
      ENV_DATABASE_FILE_LOCATION : D:\Blaise5\Settings\Credentials.db
   jobs:
     - deployment: BackupUsers
       environment:
         name: ${{parameters.Environment}}
         resourceType: virtualMachine
         tags: blaise
       strategy:
        runOnce:
          deploy: 
           steps:
             - checkout: self
           
             - task: PowerShell@2
               displayName: Backup Users
               inputs:
                 filePath: '$(Agent.BuildDirectory)/s/scripts/BackUpDatabase.ps1'
